runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: always
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: always
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: always
- url: /
  script: unused
  login: optional
  secure: always
- url: /.*/
  script: unused
  login: optional
  secure: always
- url: /_ah/.*
  script: unused
  login: optional
  secure: always
- url: /.*\.jsp
  script: unused
  login: optional
  secure: always
- url: /hello
  script: unused
  login: optional
  secure: always
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
